/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_scheduler;
import gui_scheduler.Query;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author demon
 */
public class gui_scheduler extends javax.swing.JPanel  {

    /**
     * Creates new form gui_scheduler
     */
    public gui_scheduler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        jLabel1.setText("class scheduler");

        jButton5.setText("class schedule");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("class not schedule");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("java");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("computer graphic");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("daa");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("operating system");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel1))
                                    .addComponent(jRadioButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jButton6)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton5)
                        .addGap(36, 36, 36)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
   
//    String clsss=jButton1.getText();
    
//    String clss=System.console().readLine();
    
        
   long millis = System.currentTimeMillis();
        java.sql.Date date1 = new java.sql.Date(millis);
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {                                         
            // TODO add your handling code here:
            long millis = System.currentTimeMillis();
            java.sql.Date date1 = new java.sql.Date(millis);
            System.out.println(date1);
            
            Statement stmt = null;
            try {
                stmt = db_connector.Connect().createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(gui_scheduler.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                stmt.executeQuery("use calendar");
            } catch (SQLException ex) {
                Logger.getLogger(gui_scheduler.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            String query="INSERT INTO `classes`(`date`, `class`, `schedule`) VALUES ('"+date1+"','"+clss+"','1')";
            int x=stmt.executeUpdate(query);
            if(x>0) {
                System.out.println("Ok");
                System.out.println("Class schedule,Database_Updated");
                
            }
            else {
                System.out.println("Error");
                
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(gui_scheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
			
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try {                                         
            // TODO add your handling code here:
            long millis = System.currentTimeMillis();
            java.sql.Date date1 = new java.sql.Date(millis);
            System.out.println(date1);
            
            Statement stmt = null;
            try {
                stmt = db_connector.Connect().createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(gui_scheduler.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                stmt.executeQuery("use calendar");
            } catch (SQLException ex) {
                Logger.getLogger(gui_scheduler.class.getName()).log(Level.SEVERE, null, ex);
            }
//            String clss;
            
            String query="INSERT INTO `classes`(`date`, `class`, `schedule`) VALUES ('"+date1+"','"+clss+"','0')";
            int x=stmt.executeUpdate(query);
            if(x>0) {
                System.out.println("Ok");
                System.out.println("Class not schedule,Database_Updated");
                
            }
            else {
                System.out.println("Error");
                
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(gui_scheduler.class.getName()).log(Level.SEVERE, null, ex);
        }
			
        
    }//GEN-LAST:event_jButton6ActionPerformed
    String clss="";
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
         if (jRadioButton2.isSelected()){
             clss="java";
         }
         else{
            clss=null;
         }
        System.out.println(clss);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()){
             clss="cg";
         }
         else{
            clss=null;
         }
        System.out.println(clss);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected()){
             clss="daa";
         }
         else{
            clss=null;
         }
        System.out.println(clss);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton5.isSelected()){
             clss="os";
         }
         else{
            clss=null;
         }
        System.out.println(clss);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables

     public static void  guimain() throws NullPointerException {
        JFrame f = new JFrame("frame");
        f.setSize(300, 300);
        f.setContentPane(new gui_scheduler());

        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.pack();
        f.setVisible(true);


}
}
